# Generated by Django 4.1.7 on 2023-05-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_ratings_rating_rename_rating_rating_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='discription',
            new_name='description',
        ),
    ]
